name: Build Linux

on:
  push:
  pull_request:

jobs:
  run_wolfram:
    name: Run Wolfram language code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Wolfram script
      uses: rlalik/setup-cpp-compiler@master, miRoox/wolfram-action@master
      with:
        compiler: latest
        file: Scripts/Build.wl
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
