name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: steps
        run: |
            set -eux -o pipefail
            chmod +x ./.github/workflows/install_ubuntu.sh
            WE_MODE=install bash ./.github/workflows/install_ubuntu.sh
            
      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v3.19
      # - name: Build
      #   run: |
      #       /opt/Wolfram/WolframEngine/14.1/SystemFiles/Kernel/Binaries/Linux-ARM64/wolframscript -f Scripts/BuildLibrary.wls
      # - name: upload
      #   uses: actions/upload-artifact@v4
      #   with:          
      #         # A file, directory or wildcard pattern that describes what to upload
      #         # Required.
      #         path: LibraryResources/
